route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'back'

receivers:
  - name: 'back'
    webhook_configs:
      - url: 'http://host.docker.internal:8000/alerts/alertmanager-callback'
        send_resolved: true
