route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 1s
  group_interval: 1s
  repeat_interval: 4h
  receiver: 'back'

receivers:
  - name: 'back'
    webhook_configs:
      - url: 'http://host.docker.internal:8000/alerts/alertmanager-callback'
        send_resolved: true
