version: "3"

services:
  api:
    depends_on:
      db:
        condition: service_healthy
    build:
      dockerfile: ./deploy/Dockerfile
      context: .
    restart: always
    volumes:
      - "./private.pem:/code/private.pem"
      - "./public.pem:/code/public.pem"
    ports:
      - "8000:8000"
    env_file: .env

  db:
    image: "postgres:16.0"
    restart: always
    command: postgres -c synchronous_commit=off
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    env_file: .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:v2.47.2
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - "prometheus_data:/prometheus"
      - "./prometheus:/etc/prometheus"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:10.1.5
    container_name: grafana
    restart: always
    ports:
      - "3100:3000"
    volumes:
      - "grafana_data:/var/lib/grafana"

  postgres_exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    container_name: postgres_exporter
    restart: always
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres:
  prometheus_data:
  grafana_data:
