global:
  scrape_interval: 15s

# Scrape configuration
scrape_configs:

  # Prometheus itself
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'localhost:9090' ]

  # Postgres
  - job_name: 'postgres'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'postgres_exporter:9187' ]
