global:
  scrape_interval: 15s

rule_files:
  - 'alert_rules.yml'

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - 'alertmanager:9093'

# Scrape configuration
scrape_configs:

  # Prometheus itself
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'localhost:9090' ]

  # Postgres
  - job_name: 'postgres'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'postgres_exporter:9187' ]

  # Host machine
  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:9100' ]
