"""add telegram registration

Revision ID: 3e94226b66ff
Revises: ecfb0cbd7856
Create Date: 2023-11-03 14:30:52.517679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '3e94226b66ff'
down_revision: Union[str, None] = 'ecfb0cbd7856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('email_flows_user_id_fkey', 'email_flows', type_='foreignkey')
    op.add_column('users', sa.Column('telegram_id', sa.Integer(), nullable=False))
    op.execute("UPDATE users SET telegram_id = id")
    # replace primary key
    op.drop_constraint('users_pkey', 'users', type_='primary')
    op.execute("ALTER TABLE users ADD PRIMARY KEY (telegram_id)")
    op.add_column('users', sa.Column('telegram_first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('telegram_last_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('telegram_username', sa.String(), nullable=True))
    op.create_foreign_key(None, 'email_flows', 'users', ['user_id'], ['telegram_id'])
    # ### end Alembic commands ###
    op.drop_column('users', 'id')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('users', 'telegram_username')
    op.drop_column('users', 'telegram_last_name')
    op.drop_column('users', 'telegram_first_name')
    op.drop_column('users', 'telegram_id')
    op.drop_constraint(None, 'email_flows', type_='foreignkey')
    op.create_foreign_key('email_flows_user_id_fkey', 'email_flows', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
