"""remove alert linking to user

Revision ID: 90420170b056
Revises: 269bbe9ee8dc
Create Date: 2023-11-04 05:20:01.282103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90420170b056'
down_revision: Union[str, None] = '269bbe9ee8dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('alert_deliveries_receiver_id_fkey', 'alert_deliveries', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('alert_deliveries_receiver_id_fkey', 'alert_deliveries', 'users', ['receiver_id'], ['telegram_id'])
    # ### end Alembic commands ###
